// Generated by The Mesh - Do not edit manually

// Enum Types
export type AccountAccountType = 'BS_ASSET' | 'BS_LIABILITY' | 'BS_EQUITY' | 'PL_REVENUE' | 'PL_EXPENSE';
export type AccountAccountCategory = 'CASH' | 'AR' | 'AP' | 'INVENTORY' | 'FA' | 'REVENUE' | 'COGS' | 'OPEX' | 'TAX' | 'OTHER';
export type TaxCodeTaxType = 'SALES' | 'PURCHASE' | 'EXEMPT' | 'NON_TAXABLE';
export type TaxCodeInvoiceType = 'QUALIFIED' | 'NON_QUALIFIED_80' | 'NON_QUALIFIED_50' | 'EXEMPT';
export type SegmentSegmentType = 'PC' | 'CC' | 'PRJ' | 'UNIT' | 'PF';
export type JournalHeaderJournalType = 'NORMAL' | 'ADJUSTMENT' | 'CLOSING' | 'REVERSAL' | 'ACCRUAL';
export type JournalHeaderSourceModule = 'AR' | 'AP' | 'FA' | 'CM' | 'GL' | 'TAX' | 'PROP' | 'SEC';
export type JournalHeaderStatus = 'DRAFT' | 'PENDING' | 'APPROVED' | 'POSTED' | 'REJECTED' | 'CANCELLED';
export type JournalLinePartnerType = 'CUSTOMER' | 'VENDOR' | 'EMPLOYEE' | 'INTERNAL' | 'OTHER';
export type TransactionPatternPatternCategory = 'SALES' | 'PURCHASE' | 'CASH' | 'FA' | 'TAX' | 'ADJUSTMENT';
export type TransactionPatternSourceModule = 'AR' | 'AP' | 'FA' | 'CM' | 'GL' | 'TAX' | 'PROP' | 'SEC';
export type TransactionPatternTaxHandling = 'INCLUSIVE' | 'EXCLUSIVE' | 'EXEMPT' | 'NON_TAXABLE';
export type VoucherVoucherType = 'SALES_INVOICE' | 'PURCHASE_INVOICE' | 'RECEIPT' | 'PAYMENT' | 'EXPENSE' | 'ADJUSTMENT';
export type VoucherPartnerType = 'CUSTOMER' | 'VENDOR' | 'EMPLOYEE' | 'INTERNAL';
export type VoucherStatus = 'DRAFT' | 'PENDING' | 'PROCESSED' | 'CANCELLED';

// Entity Types
/** 勘定科目マスタ */
export interface Account {
  account_code: string;
  account_name: string;
  account_type: 'BS_ASSET' | 'BS_LIABILITY' | 'BS_EQUITY' | 'PL_REVENUE' | 'PL_EXPENSE';
  account_category: 'CASH' | 'AR' | 'AP' | 'INVENTORY' | 'FA' | 'REVENUE' | 'COGS' | 'OPEX' | 'TAX' | 'OTHER';
  tax_applicable: boolean;
  currency_code: string;
  is_active: boolean;
}

/** 消費税コードマスタ（インボイス制度対応） */
export interface TaxCode {
  tax_code: string;
  tax_name: string;
  tax_rate: number;
  tax_type: 'SALES' | 'PURCHASE' | 'EXEMPT' | 'NON_TAXABLE';
  invoice_type: 'QUALIFIED' | 'NON_QUALIFIED_80' | 'NON_QUALIFIED_50' | 'EXEMPT';
  deductible_rate: number;
  effective_from: string;
  effective_to?: string;
}

/** 分析軸マスタ */
export interface Segment {
  segment_type: 'PC' | 'CC' | 'PRJ' | 'UNIT' | 'PF';
  segment_code: string;
  segment_name: string;
  parent_code?: string;
  is_active: boolean;
}

/** 仕訳ヘッダ */
export interface JournalHeader {
  journal_id: string;
  journal_number: string;
  journal_date: string;
  posting_date: string;
  fiscal_year: number;
  fiscal_period: number;
  journal_type: 'NORMAL' | 'ADJUSTMENT' | 'CLOSING' | 'REVERSAL' | 'ACCRUAL';
  source_module: 'AR' | 'AP' | 'FA' | 'CM' | 'GL' | 'TAX' | 'PROP' | 'SEC';
  source_doc_type?: string;
  source_doc_id?: string;
  description?: string;
  currency_code: string;
  exchange_rate: number;
  total_debit: number;
  total_credit: number;
  total_debit_fc?: number;
  total_credit_fc?: number;
  status: 'DRAFT' | 'PENDING' | 'APPROVED' | 'POSTED' | 'REJECTED' | 'CANCELLED';
  created_by: string;
  approved_by?: string;
  posted_at?: string;
}

/** 仕訳明細 */
export interface JournalLine {
  line_id: string;
  journal_id: string  // references JournalHeader;
  line_number: number;
  account_code: string  // references Account;
  debit_amount: number;
  credit_amount: number;
  debit_amount_fc?: number;
  credit_amount_fc?: number;
  tax_code?: string  // references TaxCode;
  tax_amount?: number;
  tax_base_amount?: number;
  pc_code?: string;
  cc_code?: string;
  project_code?: string;
  unit_code?: string;
  pf_code?: string;
  description?: string;
  partner_type?: 'CUSTOMER' | 'VENDOR' | 'EMPLOYEE' | 'INTERNAL' | 'OTHER';
  partner_code?: string;
}

/** 取引パターンマスタ */
export interface TransactionPattern {
  pattern_code: string;
  pattern_name: string;
  pattern_category: 'SALES' | 'PURCHASE' | 'CASH' | 'FA' | 'TAX' | 'ADJUSTMENT';
  source_module: 'AR' | 'AP' | 'FA' | 'CM' | 'GL' | 'TAX' | 'PROP' | 'SEC';
  debit_account_code: string  // references Account;
  credit_account_code: string  // references Account;
  tax_handling: 'INCLUSIVE' | 'EXCLUSIVE' | 'EXEMPT' | 'NON_TAXABLE';
  auto_post: boolean;
  reversal_pattern_code?: string;
  is_active: boolean;
}

/** 伝票（仕訳生成元） */
export interface Voucher {
  voucher_id: string;
  voucher_type: 'SALES_INVOICE' | 'PURCHASE_INVOICE' | 'RECEIPT' | 'PAYMENT' | 'EXPENSE' | 'ADJUSTMENT';
  voucher_date: string;
  partner_type: 'CUSTOMER' | 'VENDOR' | 'EMPLOYEE' | 'INTERNAL';
  partner_code: string;
  currency_code: string;
  exchange_rate: number;
  gross_amount: number;
  tax_amount: number;
  net_amount: number;
  pattern_code: string  // references TransactionPattern;
  tax_code: string  // references TaxCode;
  pc_code?: string;
  cc_code?: string;
  project_code?: string;
  description?: string;
  status: 'DRAFT' | 'PENDING' | 'PROCESSED' | 'CANCELLED';
  journal_id?: string  // references JournalHeader;
}

// Function Input Types
export interface GenerateJournalFromVoucherInput {
  voucher_id: string;
}

export interface ApproveJournalInput {
  journal_id: string;
  approver_id: string;
}

export interface PostJournalInput {
  journal_id: string;
}

export interface ReverseJournalInput {
  journal_id: string;
  reason: string;
}

// Error Types
export type ErrorCode = 'BALANCE_MISMATCH' | 'INVALID_PATTERN' | 'INVALID_TAX_CODE' | 'JOURNAL_NOT_APPROVED' | 'JOURNAL_NOT_PENDING' | 'JOURNAL_NOT_POSTED' | 'VOUCHER_NOT_PENDING';

export interface ErrorResponse {
  success: false;
  error: ErrorCode;
  message?: string;
}
