// Generated by The Mesh - Do not edit manually
import { z } from 'zod';

// Entity Schemas
/** 勘定科目マスタ */
export const accountSchema = z.object({
  account_code: z.string().min(1),
  account_name: z.string().min(1),
  account_type: z.enum(['BS_ASSET', 'BS_LIABILITY', 'BS_EQUITY', 'PL_REVENUE', 'PL_EXPENSE']),
  account_category: z.enum(['CASH', 'AR', 'AP', 'INVENTORY', 'FA', 'REVENUE', 'COGS', 'OPEX', 'TAX', 'OTHER']),
  tax_applicable: z.boolean(),
  currency_code: z.string().min(1),
  is_active: z.boolean(),
});

/** 消費税コードマスタ（インボイス制度対応） */
export const taxCodeSchema = z.object({
  tax_code: z.string().min(1),
  tax_name: z.string().min(1),
  tax_rate: z.number(),
  tax_type: z.enum(['SALES', 'PURCHASE', 'EXEMPT', 'NON_TAXABLE']),
  invoice_type: z.enum(['QUALIFIED', 'NON_QUALIFIED_80', 'NON_QUALIFIED_50', 'EXEMPT']),
  deductible_rate: z.number(),
  effective_from: z.string().datetime(),
  effective_to: z.string().datetime().optional(),
});

/** 分析軸マスタ */
export const segmentSchema = z.object({
  segment_type: z.enum(['PC', 'CC', 'PRJ', 'UNIT', 'PF']),
  segment_code: z.string().min(1),
  segment_name: z.string().min(1),
  parent_code: z.string().min(1).optional(),
  is_active: z.boolean(),
});

/** 仕訳ヘッダ */
export const journalHeaderSchema = z.object({
  journal_id: z.string().min(1),
  journal_number: z.string().min(1),
  journal_date: z.string().datetime(),
  posting_date: z.string().datetime(),
  fiscal_year: z.number().int(),
  fiscal_period: z.number().int(),
  journal_type: z.enum(['NORMAL', 'ADJUSTMENT', 'CLOSING', 'REVERSAL', 'ACCRUAL']),
  source_module: z.enum(['AR', 'AP', 'FA', 'CM', 'GL', 'TAX', 'PROP', 'SEC']),
  source_doc_type: z.string().min(1).optional(),
  source_doc_id: z.string().min(1).optional(),
  description: z.string().min(1).optional(),
  currency_code: z.string().min(1),
  exchange_rate: z.number(),
  total_debit: z.number().int(),
  total_credit: z.number().int(),
  total_debit_fc: z.number().int().optional(),
  total_credit_fc: z.number().int().optional(),
  status: z.enum(['DRAFT', 'PENDING', 'APPROVED', 'POSTED', 'REJECTED', 'CANCELLED']),
  created_by: z.string().min(1),
  approved_by: z.string().min(1).optional(),
  posted_at: z.string().datetime().optional(),
});

/** 仕訳明細 */
export const journalLineSchema = z.object({
  line_id: z.string().min(1),
  journal_id: z.string().min(1)  // references JournalHeader,
  line_number: z.number().int(),
  account_code: z.string().min(1)  // references Account,
  debit_amount: z.number().int(),
  credit_amount: z.number().int(),
  debit_amount_fc: z.number().int().optional(),
  credit_amount_fc: z.number().int().optional(),
  tax_code: z.string().min(1)  // references TaxCode.optional(),
  tax_amount: z.number().int().optional(),
  tax_base_amount: z.number().int().optional(),
  pc_code: z.string().min(1).optional(),
  cc_code: z.string().min(1).optional(),
  project_code: z.string().min(1).optional(),
  unit_code: z.string().min(1).optional(),
  pf_code: z.string().min(1).optional(),
  description: z.string().min(1).optional(),
  partner_type: z.enum(['CUSTOMER', 'VENDOR', 'EMPLOYEE', 'INTERNAL', 'OTHER']).optional(),
  partner_code: z.string().min(1).optional(),
});

/** 取引パターンマスタ */
export const transactionPatternSchema = z.object({
  pattern_code: z.string().min(1),
  pattern_name: z.string().min(1),
  pattern_category: z.enum(['SALES', 'PURCHASE', 'CASH', 'FA', 'TAX', 'ADJUSTMENT']),
  source_module: z.enum(['AR', 'AP', 'FA', 'CM', 'GL', 'TAX', 'PROP', 'SEC']),
  debit_account_code: z.string().min(1)  // references Account,
  credit_account_code: z.string().min(1)  // references Account,
  tax_handling: z.enum(['INCLUSIVE', 'EXCLUSIVE', 'EXEMPT', 'NON_TAXABLE']),
  auto_post: z.boolean(),
  reversal_pattern_code: z.string().min(1).optional(),
  is_active: z.boolean(),
});

/** 伝票（仕訳生成元） */
export const voucherSchema = z.object({
  voucher_id: z.string().min(1),
  voucher_type: z.enum(['SALES_INVOICE', 'PURCHASE_INVOICE', 'RECEIPT', 'PAYMENT', 'EXPENSE', 'ADJUSTMENT']),
  voucher_date: z.string().datetime(),
  partner_type: z.enum(['CUSTOMER', 'VENDOR', 'EMPLOYEE', 'INTERNAL']),
  partner_code: z.string().min(1),
  currency_code: z.string().min(1),
  exchange_rate: z.number(),
  gross_amount: z.number().int(),
  tax_amount: z.number().int(),
  net_amount: z.number().int(),
  pattern_code: z.string().min(1)  // references TransactionPattern,
  tax_code: z.string().min(1)  // references TaxCode,
  pc_code: z.string().min(1).optional(),
  cc_code: z.string().min(1).optional(),
  project_code: z.string().min(1).optional(),
  description: z.string().min(1).optional(),
  status: z.enum(['DRAFT', 'PENDING', 'PROCESSED', 'CANCELLED']),
  journal_id: z.string().min(1)  // references JournalHeader.optional(),
});

// Function Input Schemas
/** 伝票から仕訳を自動生成 */
export const generateJournalFromVoucherInputSchema = z.object({
  voucher_id: z.string().min(1),
})

// Server-side validation: voucher.status == PENDING (PENDING状態の伝票のみ仕訳生成可能)
// Server-side error check [VOUCHER_NOT_PENDING]: voucher.status != PENDING (伝票がPENDING状態ではない)
// Server-side error check [INVALID_PATTERN]: transaction_pattern.is_active == False (取引パターンが無効)
// Server-side error check [INVALID_TAX_CODE]: tax_code.tax_code == None (税コードが無効)
;

/** 仕訳の承認 */
export const approveJournalInputSchema = z.object({
  journal_id: z.string().min(1),
  approver_id: z.string().min(1),
})

// Server-side validation: journal_header.status == PENDING (PENDING状態の仕訳のみ承認可能)
// Server-side error check [JOURNAL_NOT_PENDING]: journal_header.status != PENDING (仕訳がPENDING状態ではない)
// Server-side error check [BALANCE_MISMATCH]: journal_header.total_debit != journal_header.total_credit (貸借バランスが不一致)
;

/** 仕訳の転記 */
export const postJournalInputSchema = z.object({
  journal_id: z.string().min(1),
})

// Server-side validation: journal_header.status == APPROVED (承認済み仕訳のみ転記可能)
// Server-side error check [JOURNAL_NOT_APPROVED]: journal_header.status != APPROVED (仕訳が承認済みではない)
;

/** 仕訳の取消（反対仕訳生成） */
export const reverseJournalInputSchema = z.object({
  journal_id: z.string().min(1),
  reason: z.string().min(1),
})

// Server-side validation: journal_header.status == POSTED (転記済み仕訳のみ取消可能)
// Server-side error check [JOURNAL_NOT_POSTED]: journal_header.status != POSTED (仕訳が転記済みではない)
;

// Type Exports
export type Account = z.infer<typeof accountSchema>;
export type TaxCode = z.infer<typeof taxCodeSchema>;
export type Segment = z.infer<typeof segmentSchema>;
export type JournalHeader = z.infer<typeof journalHeaderSchema>;
export type JournalLine = z.infer<typeof journalLineSchema>;
export type TransactionPattern = z.infer<typeof transactionPatternSchema>;
export type Voucher = z.infer<typeof voucherSchema>;
export type GenerateJournalFromVoucherInput = z.infer<typeof generateJournalFromVoucherInputSchema>;
export type ApproveJournalInput = z.infer<typeof approveJournalInputSchema>;
export type PostJournalInput = z.infer<typeof postJournalInputSchema>;
export type ReverseJournalInput = z.infer<typeof reverseJournalInputSchema>;