"""Tests for TypeScript Generator"""

import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from generators.typescript_gen import TypeScriptGenerator


# Sample spec for testing
SAMPLE_SPEC = {
    "meta": {
        "id": "test-system",
        "title": "Test System",
        "version": "1.0.0"
    },
    "entities": {
        "invoice": {
            "description": "Invoice entity",
            "fields": {
                "id": {"type": "string", "required": True},
                "customer_id": {"type": {"ref": "customer"}, "required": True},
                "amount": {"type": "int", "required": True},
                "discount": {"type": "float", "required": False},
                "status": {"type": {"enum": ["open", "closed", "cancelled"]}, "required": True},
                "tags": {"type": {"list": "string"}, "required": False}
            }
        },
        "customer": {
            "description": "Customer entity",
            "fields": {
                "id": {"type": "string", "required": True},
                "name": {"type": "string", "required": True},
                "active": {"type": "bool", "required": True}
            }
        }
    },
    "commands": {
        "create_invoice": {
            "description": "Create a new invoice",
            "input": {
                "customer_id": {"type": "string", "required": True},
                "amount": {"type": "int", "required": True},
                "note": {"type": "string", "required": False}
            },
            "output": {
                "invoice_id": {"type": "string", "required": True},
                "success": {"type": "bool", "required": True}
            },
            "error": [
                {"code": "CUSTOMER_NOT_FOUND", "when": {}, "reason": "Customer not found"},
                {"code": "INVALID_AMOUNT", "when": {}, "reason": "Amount must be positive"}
            ]
        },
        "close_invoice": {
            "description": "Close an invoice",
            "input": {
                "invoice_id": {"type": "string", "required": True}
            },
            "error": [
                {"code": "INVOICE_NOT_FOUND", "when": {}, "reason": "Invoice not found"},
                {"code": "ALREADY_CLOSED", "when": {}, "reason": "Already closed"}
            ]
        }
    }
}


class TestTypeScriptGenerator:
    """Test TypeScript type generation"""

    def test_generate_all(self):
        """Test generating all types"""
        gen = TypeScriptGenerator(SAMPLE_SPEC)
        result = gen.generate_all()

        # Check header
        assert "// Generated by The Mesh" in result

        # Check entity types
        assert "export interface Invoice {" in result
        assert "export interface Customer {" in result

        # Check function input types
        assert "export interface CreateInvoiceInput {" in result
        assert "export interface CloseInvoiceInput {" in result

        # Check function output types
        assert "export interface CreateInvoiceOutput {" in result

        # Check error types
        assert "export type ErrorCode =" in result

    def test_entity_interface(self):
        """Test entity interface generation"""
        gen = TypeScriptGenerator(SAMPLE_SPEC)
        result = gen.generate_for_entity("invoice")

        # Check interface structure
        assert "export interface Invoice {" in result

        # Check field types
        assert "id: string;" in result
        assert "amount: number;" in result
        assert "discount?: number;" in result  # optional
        assert "status: 'open' | 'closed' | 'cancelled';" in result
        assert "tags?: string[];" in result

        # Check reference comment
        assert "references Customer" in result

    def test_function_input_types(self):
        """Test function input type generation"""
        gen = TypeScriptGenerator(SAMPLE_SPEC)
        result = gen.generate_for_function("create_invoice")

        assert "export interface CreateInvoiceInput {" in result
        assert "customer_id: string;" in result
        assert "amount: number;" in result
        assert "note?: string;" in result  # optional

    def test_function_output_types(self):
        """Test function output type generation"""
        gen = TypeScriptGenerator(SAMPLE_SPEC)
        result = gen.generate_for_function("create_invoice")

        assert "export interface CreateInvoiceOutput {" in result
        assert "invoice_id: string;" in result
        assert "success: boolean;" in result

    def test_enum_types(self):
        """Test enum type generation"""
        gen = TypeScriptGenerator(SAMPLE_SPEC)
        result = gen.generate_all()

        # Check that enum is extracted
        assert "export type InvoiceStatus = 'open' | 'closed' | 'cancelled';" in result

    def test_error_code_union(self):
        """Test error code union type generation"""
        gen = TypeScriptGenerator(SAMPLE_SPEC)
        result = gen.generate_all()

        # Check error codes are collected
        assert "CUSTOMER_NOT_FOUND" in result
        assert "INVALID_AMOUNT" in result
        assert "INVOICE_NOT_FOUND" in result
        assert "ALREADY_CLOSED" in result

        # Check ErrorResponse interface
        assert "export interface ErrorResponse {" in result
        assert "error: ErrorCode;" in result

    def test_list_type(self):
        """Test list type conversion"""
        gen = TypeScriptGenerator(SAMPLE_SPEC)
        result = gen.generate_for_entity("invoice")

        assert "tags?: string[];" in result

    def test_description_as_jsdoc(self):
        """Test that descriptions become JSDoc comments"""
        gen = TypeScriptGenerator(SAMPLE_SPEC)
        result = gen.generate_for_entity("invoice")

        assert "/** Invoice entity */" in result

    def test_empty_spec(self):
        """Test with empty spec"""
        gen = TypeScriptGenerator({})
        result = gen.generate_all()

        assert "// Generated by The Mesh" in result
        # Should not crash with empty spec

    def test_to_pascal_case(self):
        """Test snake_case to PascalCase conversion"""
        gen = TypeScriptGenerator({})

        assert gen._to_pascal_case("invoice") == "Invoice"
        assert gen._to_pascal_case("line_item") == "LineItem"
        assert gen._to_pascal_case("customer_address_type") == "CustomerAddressType"

    def test_ref_type_generates_comment(self):
        """Test that ref types include a comment about the reference"""
        gen = TypeScriptGenerator(SAMPLE_SPEC)
        result = gen.generate_for_entity("invoice")

        # customer_id should have a comment indicating it references Customer
        assert "customer_id: string  // references Customer" in result


class TestTypeScriptGeneratorEdgeCases:
    """Test edge cases for TypeScript generator"""

    def test_nested_list_type(self):
        """Test nested list types (list of lists)"""
        spec = {
            "entities": {
                "matrix": {
                    "fields": {
                        "rows": {"type": {"list": {"list": "int"}}, "required": True}
                    }
                }
            }
        }
        gen = TypeScriptGenerator(spec)
        result = gen.generate_for_entity("matrix")

        assert "rows: number[][];" in result

    def test_unknown_type(self):
        """Test handling of unknown types"""
        spec = {
            "entities": {
                "test": {
                    "fields": {
                        "weird": {"type": "weird_type", "required": True}
                    }
                }
            }
        }
        gen = TypeScriptGenerator(spec)
        result = gen.generate_for_entity("test")

        assert "weird: unknown;" in result

    def test_function_without_output(self):
        """Test function without output definition"""
        spec = {
            "commands": {
                "delete_something": {
                    "input": {
                        "id": {"type": "string", "required": True}
                    }
                }
            }
        }
        gen = TypeScriptGenerator(spec)
        result = gen.generate_all()

        assert "DeleteSomethingInput" in result
        assert "DeleteSomethingOutput" not in result

    def test_function_without_input(self):
        """Test function without input definition"""
        spec = {
            "commands": {
                "get_all": {
                    "output": {
                        "items": {"type": {"list": "string"}, "required": True}
                    }
                }
            }
        }
        gen = TypeScriptGenerator(spec)
        result = gen.generate_all()

        assert "GetAllInput" not in result
        assert "GetAllOutput" in result


if __name__ == "__main__":
    import pytest
    pytest.main([__file__, "-v"])
