"""Tests for Zod Generator"""

import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from generators.zod_gen import ZodGenerator


# Sample spec for testing
SAMPLE_SPEC = {
    "meta": {
        "id": "test-system",
        "title": "Test System",
        "version": "1.0.0"
    },
    "entities": {
        "invoice": {
            "description": "Invoice entity",
            "fields": {
                "id": {"type": "string", "required": True},
                "customer_id": {"type": {"ref": "customer"}, "required": True},
                "amount": {"type": "int", "required": True},
                "discount": {"type": "float", "required": False},
                "status": {"type": {"enum": ["open", "closed", "cancelled"]}, "required": True},
                "tags": {"type": {"list": "string"}, "required": False}
            }
        },
        "customer": {
            "description": "Customer entity",
            "fields": {
                "id": {"type": "string", "required": True},
                "name": {"type": "string", "required": True},
                "active": {"type": "bool", "required": True}
            }
        }
    },
    "commands": {
        "create_invoice": {
            "description": "Create a new invoice",
            "input": {
                "customer_id": {"type": "string", "required": True},
                "amount": {"type": "int", "required": True},
                "note": {"type": "string", "required": False}
            },
            "pre": [
                {
                    "expr": {
                        "type": "binary",
                        "op": "gt",
                        "left": {"type": "input", "name": "amount"},
                        "right": {"type": "literal", "value": 0}
                    },
                    "reason": "Amount must be positive"
                }
            ],
            "error": [
                {"code": "CUSTOMER_NOT_FOUND", "when": {"type": "ref", "path": "customer"}, "reason": "Customer not found"}
            ]
        },
        "allocate_payment": {
            "description": "Allocate payment to invoice",
            "input": {
                "invoice_id": {"type": "string", "required": True},
                "payment_id": {"type": "string", "required": True},
                "amount": {"type": "int", "required": True}
            },
            "pre": [
                {
                    "expr": {
                        "type": "binary",
                        "op": "le",
                        "left": {"type": "input", "name": "amount"},
                        "right": {"type": "literal", "value": 1000000}
                    },
                    "reason": "Amount cannot exceed 1,000,000"
                },
                {
                    "expr": {
                        "type": "ref",
                        "path": "invoice.status"
                    },
                    "reason": "Invoice must be open"
                }
            ]
        }
    }
}


class TestZodGenerator:
    """Test Zod schema generation"""

    def test_generate_all(self):
        """Test generating all Zod schemas"""
        gen = ZodGenerator(SAMPLE_SPEC)
        result = gen.generate_all()

        # Check header
        assert "// Generated by The Mesh" in result
        assert "import { z } from 'zod';" in result

        # Check entity schemas
        assert "invoiceSchema = z.object({" in result
        assert "customerSchema = z.object({" in result

        # Check function input schemas
        assert "createInvoiceInputSchema = z.object({" in result
        assert "allocatePaymentInputSchema = z.object({" in result

        # Check type exports
        assert "export type Invoice = z.infer<typeof invoiceSchema>;" in result

    def test_entity_schema(self):
        """Test entity schema generation"""
        gen = ZodGenerator(SAMPLE_SPEC)
        result = gen.generate_for_entity("invoice")

        # Check schema structure
        assert "invoiceSchema = z.object({" in result

        # Check field types
        assert "id: z.string().min(1)," in result
        assert "amount: z.number().int()," in result
        assert "discount: z.number().optional()," in result
        assert "active: z.boolean()" not in result  # from customer, not invoice

    def test_enum_type(self):
        """Test enum field type generation"""
        gen = ZodGenerator(SAMPLE_SPEC)
        result = gen.generate_for_entity("invoice")

        assert "status: z.enum(['open', 'closed', 'cancelled'])," in result

    def test_list_type(self):
        """Test list field type generation"""
        gen = ZodGenerator(SAMPLE_SPEC)
        result = gen.generate_for_entity("invoice")

        assert "tags: z.array(z.string().min(1)).optional()," in result

    def test_ref_type(self):
        """Test ref field type generation"""
        gen = ZodGenerator(SAMPLE_SPEC)
        result = gen.generate_for_entity("invoice")

        # Ref should be string with comment
        assert "customer_id: z.string().min(1)  // references Customer," in result

    def test_optional_fields(self):
        """Test optional field handling"""
        gen = ZodGenerator(SAMPLE_SPEC)
        result = gen.generate_for_entity("invoice")

        # Required fields should not have .optional()
        assert "id: z.string().min(1)," in result
        # Optional fields should have .optional()
        assert "discount: z.number().optional()," in result

    def test_function_input_schema(self):
        """Test function input schema generation"""
        gen = ZodGenerator(SAMPLE_SPEC)
        result = gen.generate_for_function("create_invoice")

        assert "createInvoiceInputSchema = z.object({" in result
        assert "customer_id: z.string().min(1)," in result
        assert "amount: z.number().int()," in result
        assert "note: z.string().min(1).optional()," in result

    def test_refinement_from_pre_condition(self):
        """Test refinement generation from pre conditions"""
        gen = ZodGenerator(SAMPLE_SPEC)
        result = gen.generate_for_function("create_invoice")

        # Should have refinement for amount > 0
        assert ".refine(data => data.amount > 0" in result
        assert 'message: "Amount must be positive"' in result

    def test_literal_comparison_refinement(self):
        """Test literal comparison refinement"""
        gen = ZodGenerator(SAMPLE_SPEC)
        result = gen.generate_for_function("allocate_payment")

        # Should have refinement for amount <= 1000000
        assert ".refine(data => data.amount <= 1000000" in result

    def test_server_side_validation_comment(self):
        """Test server-side-only validations are marked as comments"""
        gen = ZodGenerator(SAMPLE_SPEC)
        result = gen.generate_for_function("allocate_payment")

        # Ref-based validation should be marked as server-side
        assert "// Server-side validation:" in result

    def test_error_condition_as_server_side(self):
        """Test that error conditions with refs are marked as server-side"""
        gen = ZodGenerator(SAMPLE_SPEC)
        result = gen.generate_for_function("create_invoice")

        # Error with ref should be marked as server-side
        assert "// Server-side error check [CUSTOMER_NOT_FOUND]:" in result

    def test_description_as_jsdoc(self):
        """Test that descriptions become JSDoc comments"""
        gen = ZodGenerator(SAMPLE_SPEC)
        result = gen.generate_for_entity("invoice")

        assert "/** Invoice entity */" in result

    def test_type_exports(self):
        """Test TypeScript type exports from Zod schemas"""
        gen = ZodGenerator(SAMPLE_SPEC)
        result = gen.generate_all()

        # Entity types
        assert "export type Invoice = z.infer<typeof invoiceSchema>;" in result
        assert "export type Customer = z.infer<typeof customerSchema>;" in result

        # Function input types
        assert "export type CreateInvoiceInput = z.infer<typeof createInvoiceInputSchema>;" in result

    def test_empty_spec(self):
        """Test with empty spec"""
        gen = ZodGenerator({})
        result = gen.generate_all()

        assert "// Generated by The Mesh" in result
        assert "import { z } from 'zod';" in result
        # Should not crash with empty spec

    def test_to_camel_case(self):
        """Test snake_case to camelCase conversion"""
        gen = ZodGenerator({})

        assert gen._to_camel_case("invoice") == "invoice"
        assert gen._to_camel_case("line_item") == "lineItem"
        assert gen._to_camel_case("customer_address_type") == "customerAddressType"

    def test_to_pascal_case(self):
        """Test snake_case to PascalCase conversion"""
        gen = ZodGenerator({})

        assert gen._to_pascal_case("invoice") == "Invoice"
        assert gen._to_pascal_case("line_item") == "LineItem"


class TestZodGeneratorEdgeCases:
    """Test edge cases for Zod generator"""

    def test_function_without_input(self):
        """Test function without input definition"""
        spec = {
            "commands": {
                "get_status": {
                    "description": "Get status"
                }
            }
        }
        gen = ZodGenerator(spec)
        result = gen.generate_all()

        assert "getStatusInputSchema" not in result

    def test_function_without_pre(self):
        """Test function without pre conditions"""
        spec = {
            "commands": {
                "simple_action": {
                    "input": {
                        "id": {"type": "string", "required": True}
                    }
                }
            }
        }
        gen = ZodGenerator(spec)
        result = gen.generate_for_function("simple_action")

        # Should have schema but no refinements
        assert "simpleActionInputSchema = z.object({" in result
        assert ".refine(" not in result

    def test_datetime_type(self):
        """Test datetime type conversion"""
        spec = {
            "entities": {
                "event": {
                    "fields": {
                        "created_at": {"type": "datetime", "required": True}
                    }
                }
            }
        }
        gen = ZodGenerator(spec)
        result = gen.generate_for_entity("event")

        assert "created_at: z.string().datetime()," in result

    def test_text_type(self):
        """Test text type conversion"""
        spec = {
            "entities": {
                "note": {
                    "fields": {
                        "content": {"type": "text", "required": True}
                    }
                }
            }
        }
        gen = ZodGenerator(spec)
        result = gen.generate_for_entity("note")

        # text should be z.string() without min(1)
        assert "content: z.string()," in result

    def test_binary_expression_field_vs_field(self):
        """Test refinement for comparing two input fields"""
        spec = {
            "commands": {
                "transfer": {
                    "input": {
                        "start_date": {"type": "string", "required": True},
                        "end_date": {"type": "string", "required": True}
                    },
                    "pre": [
                        {
                            "expr": {
                                "type": "binary",
                                "op": "lt",
                                "left": {"type": "input", "name": "start_date"},
                                "right": {"type": "input", "name": "end_date"}
                            },
                            "reason": "Start date must be before end date"
                        }
                    ]
                }
            }
        }
        gen = ZodGenerator(spec)
        result = gen.generate_for_function("transfer")

        assert ".refine(data => data.start_date < data.end_date" in result

    def test_aggregation_requires_server_side(self):
        """Test that aggregation expressions require server-side validation"""
        spec = {
            "commands": {
                "check_count": {
                    "input": {
                        "limit": {"type": "int", "required": True}
                    },
                    "pre": [
                        {
                            "expr": {
                                "type": "agg",
                                "op": "count",
                                "from": "invoice"
                            },
                            "reason": "Check invoice count"
                        }
                    ]
                }
            }
        }
        gen = ZodGenerator(spec)
        result = gen.generate_for_function("check_count")

        # Aggregation should be marked as server-side
        assert "// Server-side validation:" in result
        assert "count(invoice)" in result

    def test_unknown_type_handling(self):
        """Test handling of unknown types"""
        spec = {
            "entities": {
                "test": {
                    "fields": {
                        "weird": {"type": "weird_type", "required": True}
                    }
                }
            }
        }
        gen = ZodGenerator(spec)
        result = gen.generate_for_entity("test")

        assert "weird: z.unknown()," in result

    def test_entity_not_found(self):
        """Test generating for non-existent entity"""
        gen = ZodGenerator({})
        result = gen.generate_for_entity("nonexistent")

        assert "// Entity not found: nonexistent" in result

    def test_function_not_found(self):
        """Test generating for non-existent function"""
        gen = ZodGenerator({})
        result = gen.generate_for_function("nonexistent")

        assert "// Function not found: nonexistent" in result


if __name__ == "__main__":
    import pytest
    pytest.main([__file__, "-v"])
